org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
# Miuix 0.9.2 要求 compileSdk 37，超出 AGP 8.13 的推荐范围
android.suppressUnsupportedCompileSdk=37,37.0

kotlin.code.style=official
